# Generated by Django 5.1.15 on 2026-02-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_hours',
            field=models.PositiveIntegerField(default=3, help_text='Weekly hours (e.g. 2, 3, 4)'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_start_date',
            field=models.DateField(blank=True, help_text='First day of semester — used to auto-generate 14 weeks of sessions', null=True),
        ),
    ]
