# Generated by Django 6.0.2 on 2026-02-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_enrollment_final_grade_enrollment_midterm_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
