# Generated by Django 6.0.2 on 2026-02-17 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcusedAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(help_text='e.g. "Medical report", "Official leave"', max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excused_absences', to='attendance.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excused_absences', to='attendance.student')),
            ],
            options={
                'ordering': ['session__date'],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
