# Generated by Django 6.0.2 on 2026-02-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_excused_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.CharField(blank=True, help_text='e.g. Dr. Fatih Bozdag', max_length=200),
        ),
    ]
