# Generated by Django 6.0.2 on 2026-02-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_course_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='student_id_entered',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student'], name='attendance__student_bf8a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['course', 'is_cancelled'], name='attendance__course__916cce_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['course', 'date'], name='attendance__course__3f64a4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course'], name='attendance__course__fecdb9_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='attendance__student_f70cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='excusedabsence',
            index=models.Index(fields=['student', 'session'], name='attendance__student_3c6bec_idx'),
        ),
    ]
