# Generated by Django 6.0.2 on 2026-02-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
